### ISSUE TITLE
Automating IP changes

### ISSUE THREAD

**Issue by lightc786** [tonikelope/megabasterd#113]
So using the smartproxy slows down downloads considerably and I was thinking it might be nice to have a way to automate IP changes similar to the way that Jdownloader allows you to run IP change scripts when you hit your download limit.

Is this something that's possible with megabasterd?

**Comment by necros2k7** [comment]
> So using the smartproxy slows down downloads considerably and I was thinking it might be nice to have a way to automate IP changes similar to the way that Jdownloader allows you to run IP change scripts when you hit your download limit.
> 
> Is this something that's possible with megabasterd?

something like fast ProtonVPN, Epic browser?

**Comment by lightc786** [comment]
Well, just an ability to run a user defined script when a bandwidth limit
is reached with mega would be useful.

With JDownloader you can set it to run a script to reboot your modem or
router to get a new ip address if you have a provider that has a dynamic
IP. Then jdownloader automatically resumes the download when it detects a
successful ip change.

**Comment by tonikelope** [comment]
If I have time, I will study the option of running an external script or application when the 509 bandwidth error first comes up.

Regards.

**Comment by tonikelope** [comment]
Done. Check Advanced Settings

**Comment by MeesaSonJay** [comment]
I think this issue is not fully resolved. Upon attempting to download a large file (like 20 GB), the script will be executed correctly at around 4 - 5 GB. However, at the next 5 GB data limit, the script is not executed. I do know it is a data cap because if I refresh my IP, the download continues. The script gets executed 1/3 - 1/4 times for a large file, so I think there are other HTTP errors or data cap limit errors that I cannot observe. Is this an issue on my end or is there another flag/error missing on the if condition?
