### ISSUE TITLE
downloads stuck at near completion.

### ISSUE THREAD

**Issue by glh290** [tonikelope/megabasterd#168]
If II'm downloading more than 3 files, (i set my lit to 3 because if i do more the stuck downloads increase) 1 of the files will get stuck at 99 or 100%  canceling the download seems to fix this 10% of the time, but canceling and deleting the temp file then restarting the app usually results in the download completing. im using 6.88 I've experienced this on the last few releases aswell, but the 6.88 seems to have a better chance at restarting the download with a a temp file, but will still have to need the temp file deleted and the app restarted.

**Comment by tonikelope** [comment]
There have been no significant changes in the latest versions that could produce such behavior and with the tests I've done I can't reproduce it. However, run MegaBasterd from the command prompt and paste the complete log here so that you have some information with which to analyze what might be happening to you.

`java -jar MegaBasterd_6.88 > log.txt`

**Comment by vincentmathis** [comment]
I had the same problem: Downloads stopping at 100% with status "Downloading file from mega ..." but the speed was "-------".

I was using the Windows Portable .exe so far but I just restarted it using the .jar instead and now it the status says "Download finished. Joining file chunks, please wait ..." . So far it seems to work.

**Comment by Nikita11790** [comment]
yea I have same issue

**Comment by Nikita11790** [comment]
seems fixed in latest update

**Comment by noah1gamble** [comment]
This problem persists so idk why you closed it.

![image](https://user-images.githubusercontent.com/11571144/96936813-c05d7e00-1494-11eb-98bc-be3fbd857303.png)

Pretty trash program
